// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/chai-splash/Polished.tsx": () => import("../components/mockups/chai-splash/Polished.tsx"),
  "./components/mockups/cinematic-mobile/Hero.tsx": () => import("../components/mockups/cinematic-mobile/Hero.tsx"),
  "./components/mockups/design-system/SystemShowcase.tsx": () => import("../components/mockups/design-system/SystemShowcase.tsx"),
  "./components/mockups/gameplay-direction/Desktop.tsx": () => import("../components/mockups/gameplay-direction/Desktop.tsx"),
  "./components/mockups/gameplay-direction/Mobile.tsx": () => import("../components/mockups/gameplay-direction/Mobile.tsx"),
  "./components/mockups/scenes/JoeyLaundryCombinedStrike.tsx": () => import("../components/mockups/scenes/JoeyLaundryCombinedStrike.tsx"),
  "./components/mockups/scenes/JoeyLaundryPawStrike.tsx": () => import("../components/mockups/scenes/JoeyLaundryPawStrike.tsx"),
  "./components/mockups/scenes/JoeyLaundrySockDrop.tsx": () => import("../components/mockups/scenes/JoeyLaundrySockDrop.tsx"),
  "./components/mockups/scenes/LapQuestLedge.tsx": () => import("../components/mockups/scenes/LapQuestLedge.tsx"),
  "./components/mockups/scenes/LapQuestLedgeExitInactivity.tsx": () => import("../components/mockups/scenes/LapQuestLedgeExitInactivity.tsx"),
  "./components/mockups/scenes/LapQuestLedgeExitJoey.tsx": () => import("../components/mockups/scenes/LapQuestLedgeExitJoey.tsx"),
  "./components/mockups/scenes/LapQuestReveal.tsx": () => import("../components/mockups/scenes/LapQuestReveal.tsx"),
  "./components/mockups/scenes/LapQuestRoundPlay.tsx": () => import("../components/mockups/scenes/LapQuestRoundPlay.tsx"),
  "./components/mockups/scenes/UnigleeActKeepsakeCollection.tsx": () => import("../components/mockups/scenes/UnigleeActKeepsakeCollection.tsx"),
  "./components/mockups/scenes/UnigleeActNighttimeTreatTime.tsx": () => import("../components/mockups/scenes/UnigleeActNighttimeTreatTime.tsx"),
  "./components/mockups/scenes/UnigleeActWereMultiplying.tsx": () => import("../components/mockups/scenes/UnigleeActWereMultiplying.tsx"),
  "./components/mockups/scenes/UnigleeChapterBanner.tsx": () => import("../components/mockups/scenes/UnigleeChapterBanner.tsx"),
  "./components/mockups/scenes/UnigleeMarathonLevelup.tsx": () => import("../components/mockups/scenes/UnigleeMarathonLevelup.tsx"),
  "./components/mockups/progress-feedback/Playful.tsx": () => import("../components/mockups/progress-feedback/Playful.tsx"),
  "./components/mockups/storybook-opening/Desktop.tsx": () => import("../components/mockups/storybook-opening/Desktop.tsx")
};
