// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/chai-splash/Polished.tsx": () => import("../components/mockups/chai-splash/Polished.tsx")
};
